%% In theory
gitGraph
%%    create branches
    commit id: "main"
    branch A
    branch B
%% Normal
%%    A first
    checkout A
    commit tag: "a.1"
    checkout B
    commit tag: "b.1"
%% Stagger
    checkout A
    commit tag: "a.2"
    checkout B
    commit tag: "b.2"

%%    Merge Both into Main
    checkout main
    merge A
    merge B

